# Generated by Django 3.0.3 on 2020-03-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasyworld.League')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasyworld.LeagueSession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasyworld.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('league_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasyworld.LeagueType')),
            ],
        ),
        migrations.AddField(
            model_name='leaguesession',
            name='members',
            field=models.ManyToManyField(through='fantasyworld.Team', to='fantasyworld.Profile'),
        ),
    ]
