# Generated by Django 3.0.3 on 2020-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0006_auto_20200322_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='Team', max_length=100),
        ),
    ]
