# Generated by Django 3.0.3 on 2020-03-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0007_team_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='leaguetype',
            name='game_type',
            field=models.ManyToManyField(to='fantasyworld.GameType'),
        ),
    ]
