# Generated by Django 3.0.3 on 2020-03-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0009_auto_20200325_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='budget',
            field=models.FloatField(default=100),
        ),
    ]
