# Generated by Django 3.0.3 on 2020-03-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0010_team_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
