# Generated by Django 3.0.3 on 2020-04-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0011_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
