# Generated by Django 3.0.3 on 2020-04-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0012_stock_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguetype',
            name='positions',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
