# Generated by Django 3.0.3 on 2020-04-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0013_leaguetype_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(default='Generic', max_length=100),
        ),
    ]
