# Generated by Django 3.0.3 on 2020-04-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0016_leaguetype_meta_leaguetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetype',
            name='meta_leaguetype',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasyworld.LeagueType'),
        ),
    ]
