# Generated by Django 3.0.3 on 2020-05-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0017_auto_20200415_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguetype',
            name='how_to_play',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
