# Generated by Django 3.0.3 on 2020-05-23 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0018_leaguetype_how_to_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='league_session',
        ),
        migrations.CreateModel(
            name='StockSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Stock Set', max_length=200)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('league_session', models.ManyToManyField(default=None, to='fantasyworld.LeagueSession')),
                ('superset_stockset', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasyworld.StockSet')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fantasyworld.StockSet'),
            preserve_default=False,
        ),
    ]
