# Generated by Django 3.0.3 on 2020-05-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0019_auto_20200523_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
