# Generated by Django 3.0.3 on 2020-05-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0020_league_league_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetype',
            name='game_type',
            field=models.ManyToManyField(default=None, to='fantasyworld.GameType'),
        ),
    ]
