# Generated by Django 3.0.3 on 2020-05-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0021_auto_20200524_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaguetype',
            name='game_type',
            field=models.ManyToManyField(blank=True, default=None, to='fantasyworld.GameType'),
        ),
        migrations.AlterField(
            model_name='leaguetype',
            name='how_to_play',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='leaguetype',
            name='stock_types',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
