# Generated by Django 3.0.3 on 2020-05-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyworld', '0022_auto_20200524_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockset',
            name='league_type',
            field=models.ManyToManyField(blank=True, default=None, to='fantasyworld.LeagueType'),
        ),
        migrations.AlterField(
            model_name='stockset',
            name='league_session',
            field=models.ManyToManyField(blank=True, default=None, to='fantasyworld.LeagueSession'),
        ),
    ]
